### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by JEBailey** [sigaloid/vial#16]
Currently, the master branch can't be built due to issues with bundler.rs that I believe are windows dependent. I understand that you aren't developing on it, but is it planned to support windows?

**Comment by sigaloid** [comment]
Unfortunately I don't have a windows machine. I would love to expand support to windows if possible; which dependency is linux-only?

**Comment by JEBailey** [comment]
Honestly it's some weird stuff, as if what gets imported by default is dependant on the OS. I need to set up my linux machine and confirm everything before I submit changes. You seem to be familiar with the actions on github, is there a way to set up one for windows?

**Comment by sigaloid** [comment]
Only windows server is available with Github Actions, unfortunately, and I don't think that it's compatible. I'll hopefully get a VM set up soon or a spare laptop. 

There should be a Linux subsystem for windows. Not actually, but it would certainly make this easier :p

**Comment by JEBailey** [comment]
I ran across this and leaving it here as a reference so I can work on this later. https://github.com/rust-lang/rustfmt/blob/master/.github/workflows/windows.yml

**Comment by sigaloid** [comment]
Ohh, you can indeed! Thanks, I'll add it.

**Comment by sigaloid** [comment]
Actually, we don't even need it; `cargo check --target x86_64-pc-windows-msvc` is a thing :sweat_smile:

**Comment by sigaloid** [comment]
Now it's the `file_size` test that fails (different size on different platform). I assume the `\n` vs `\r\n` debacle... I will try to fix it later :D

**Comment by sigaloid** [comment]
Tentatively closing this as github actions windows build is now passing successfully. I haven't actually tested it on windows but at least the build is succeeding :smile: if anyone has any problems with windows feel free to reopen
